### ISSUE TITLE
How can i use it to get list of all vout and vin ?

### ISSUE THREAD

**Issue by rawmaterials** [dcousens/fast-dat-parser#13]
i have successfully compiled on my centos and did

cat ~/.bitcoin/blocks/blk*.dat | ./parser -t0 | ./bestchain > chain.dat

cat ~/.bitcoin/blocks/blk*.dat | ./parser -j4 -t1 -wchain.dat > scripts.dat

whats next ?

sorry but this whole binary thing is kinda confusing for me., 

thanks for your time.

**Comment by dcousens** [comment]
What format do you want the list of `vout` and `vin`?   What data are you after specifically?

**Comment by rawmaterials** [comment]
i am looking for 
in vin
txid , indexout 

in vout 
txid , index , amount , address.


so i can insert this data in mysql . and then later calculate addresses having positive balance.
Thanks.

**Comment by dcousens** [comment]
Sounds like you want a UTXO set?
