### ISSUE TITLE
could I use this to export my blk*.dat file to a human readable form? 

### ISSUE THREAD

**Issue by s-matthew-english** [dcousens/fast-dat-parser#4]
I generated some local test net blocks here: 

https://github.com/s-matthew-english/local_testnet

and I'd like to parse them in human readable form- can this tool do that?

**Comment by dcousens** [comment]
Sure,  depending on what you'd like to output.
This is just a parser,  you can make it output whatever you'd like.

**Comment by dcousens** [comment]
@s-matthew-english how'd you go?
